### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by ghost** [martinslabber/ansible_modules-proxmox#1]
Tried your example but get:

PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
<localhost> ESTABLISH CONNECTION FOR USER: jocke
<localhost> REMOTE_MODULE setup
<localhost> EXEC ['sshpass', '-d4', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jocke/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1410942009.74-162539436475284 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1410942009.74-162539436475284 && echo $HOME/.ansible/tmp/ansible-tmp-1410942009.74-162539436475284'"]
<localhost> PUT /tmp/tmpsfHg_3 TO /home/jocke/.ansible/tmp/ansible-tmp-1410942009.74-162539436475284/setup
<localhost> EXEC ['sshpass', '-d4', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jocke/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'ConnectTimeout=10', 'localhost', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=syhvwremgixkntytvqijdupnssummygp] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-syhvwremgixkntytvqijdupnssummygp; LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python /home/jocke/.ansible/tmp/ansible-tmp-1410942009.74-162539436475284/setup; rm -rf /home/jocke/.ansible/tmp/ansible-tmp-1410942009.74-162539436475284/ >/dev/null 2>&1\'"\'"\'\'']
ok: [localhost]

TASK: [Run module proxmoxer_ct] ***********************************************
<localhost> ESTABLISH CONNECTION FOR USER: jocke
<localhost> REMOTE_MODULE proxmoxer_ct state=started hostname=localhost username=root password=VALUE_HIDDEN ct_ostemplate='debian-7.0-standard_7.0.2_i386.tar.gz'
<localhost> EXEC ['sshpass', '-d7', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jocke/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'ConnectTimeout=10', 'localhost', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1410942011.21-39420836582169 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1410942011.21-39420836582169 && echo $HOME/.ansible/tmp/ansible-tmp-1410942011.21-39420836582169'"]
<localhost> PUT /tmp/tmpZLqRZN TO /home/jocke/.ansible/tmp/ansible-tmp-1410942011.21-39420836582169/proxmoxer_ct
<localhost> EXEC ['sshpass', '-d7', 'ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/jocke/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'GSSAPIAuthentication=no', '-o', 'PubkeyAuthentication=no', '-o', 'ConnectTimeout=10', 'localhost', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=ryflcflucludgerwsjuypqedgwzxnadq] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-ryflcflucludgerwsjuypqedgwzxnadq; LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/env python /home/jocke/.ansible/tmp/ansible-tmp-1410942011.21-39420836582169/proxmoxer_ct; rm -rf /home/jocke/.ansible/tmp/ansible-tmp-1410942011.21-39420836582169/ >/dev/null 2>&1\'"\'"\'\'']
failed: [localhost] => {"failed": true}
msg: 'dict' object is not callable

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/jocke/main.retry

localhost                  : ok=1    changed=0    unreachable=0    failed=1

**Comment by martinslabber** [comment]
Hi, thanks for trying this.  I could not guess from the above output what is wrong, not ansible experienced enough. I tried reproducing it but did not get the same error. What is obvious is that an exception is raised and its not handled correctly. 

For starters I updated the README to show how I use it. Hope there is something in there that helps.

1) In your playbook - hostname should be the hostname or IP address of the proxmox server.
2) You should give a container id. As ct_id.
3) Can you please send me your playbook and the command line you used to run it with. 
4) The ansible and proxmoxer version you user (pip list) 

Again thanks for trying it out.
